### ISSUE TITLE
PGPCore has a new version now with EncryptAndSign 

### ISSUE THREAD

**Issue by swalde** [lfalck/AzureFunctionsPGPEncrypt#1]
PGPCore has a new version now with Encrypt**AndSign** as required by many implementations

**Comment by lfalck** [comment]
That is good! And you would like me to add support for EncryptAndSign in the Azure Function?

**Comment by Dippenaarj** [comment]
Hi, we are using this in a flow (thank you), but it seems the file name comes out as 'name.txt' when the file is decrypted. Is there a way to call the function and send the 'filename'?

**Comment by lfalck** [comment]
Hi!

There is no file name used in the function, is that something from your flow or have you modified the code?

**Comment by muhammadanaskhan** [comment]
Hi @lfalck - I am calling this Azure function to encrypt the file in a Microsoft Flow as part of an integration between two systems. Encryption is being done successfully. However, when the system at the other end of the integration decrypts the file, it changes the incoming file name from "EncryptedFileName.csv.gpg" to "name.txt".

My guess is that, some systems expect the original filename embedded within the encrypted file. If they couldn't find the embedded filename in the encrypted file, they use any default filename like "name.txt". Is there a way to pass original filename to the encrypt method so that it could be embedded within the encrypted file?

I guess PGPCore is based on the Bouncy Castle API. Is there a way in the Bouncy Castle API to embed the original filename in the encrypted file?

Any help would be much appreciated! Thanks!

CC: @Dippenaarj

**Comment by lfalck** [comment]
Hi!

I don't think so, since the data is passed in the body of an http call and the encrypted results are returned in the http response body, there are really no files or file names being used at all.

Sounds like it is the system at the other end that needs some configuration change to set the file name correctly after decrypting.

**Comment by Dippenaarj** [comment]
Hi,

Thank you Ifalck, much appreciated.

Cheers

Jan
